name: Bump kotlin shadow

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  push-kotlin-nightlies-branch:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Bump Kotlin in libraries.toml
        run: ./scripts/bump-kotlin-in-libraries-toml.main.kts
      - name: Push changes to kotlin-nightlies branch
        run: |
          git add .
          git commit -m "Bump Kotlin version"
          git push --force origin kotlin-nightlies
