name: pr

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

# Cancel any current or previous job from the same PR
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  show-informations:
    steps:
      run: |
        echo ${{ startsWith(github.ref_name, 'release-') != true }}
        echo ${{ startsWith(github.ref_name, 'release-') }}
        echo ${{ github.ref_name }}
